### ISSUE TITLE
Add ivy integration

### ISSUE THREAD

**Issue by myTerminal** [myTerminal/theme-looper#8]
This is in continuation to suggestions by @4goodapp in https://github.com/myTerminal/theme-looper/issues/6 and https://github.com/myTerminal/theme-looper/issues/7.

The idea is to create an extra method to be able to switch themes interactively using ivy's `ivy-read` API.

**Comment by myTerminal** [comment]
@4goodapp I implement a simple function `theme-looper-select-theme` that uses ivy's completion interface is available and lets you select a theme from the list of your favorites.

If possible, could you please try it out and provide your feedback?

**Comment by myTerminal** [comment]
Closing this one as it seems to serve the purpose. @4goodapp, feel free to re-open just in case.

**Comment by 4goodapp** [comment]
Sorry for the delay...

I just test it. It works but I was expecting it to change the theme while scrolling through the list.
With the current implementation, I have to hit Enter to activate it. So maybe add an option for that?

**Comment by myTerminal** [comment]
I have a snippet in place that tries to find a theme and enable it while you type. However, to have it enable whatever I scroll to has not been working for me yet. I'll keep investigating.

Besides, to switch the theme on every selection change, does that not sound a little too heavy?

**Comment by 4goodapp** [comment]
> I have a snippet in place that tries to find a theme and enable it while you type. 

I think that is already a good start.

**Comment by 4goodapp** [comment]
>  Besides, to switch the theme on every selection change, does that not sound a little too heavy?

Am not sure what  you mean by heavy but if you mean performance wise, then maybe yes but the thing is with the current implementation, it's almost the same as using the function `load-theme`.

**Comment by myTerminal** [comment]
> Am not sure what you mean by heavy but if you mean performance wise, then maybe yes but the thing is with the current implementation, it's almost the same as using the function `load-theme`.

Yes, heavy but not so much. I meant to say that it is a very good idea but I have not seen an implementation like that yet. Besides, it must be a 'heavy' operation for me from the sense that in a few of my development environments at work, it takes about 55 seconds for the editor to launch and about 2 seconds for almost every file-read operation. Somehow I have developed a different sense of such processes. :)

**Comment by 4goodapp** [comment]
ahh, I see.
Then maybe make it optional and disable it by default?

> I have a snippet in place that tries to find a theme and enable it while you type. 

I'd like to test this version too. any link to try it?

**Comment by myTerminal** [comment]
> I'd like to test this version too. any link to try it?

Sure! Pardon my code though :)

    (defun theme-looper-select-theme ()
      "Lets user select a theme from a list of favorite ones rendered using ivy API"
      (interactive)
      (if (featurep 'ivy)
          (ivy-read "theme-looper: "
                    (theme-looper--get-looped-themes)
                    :action (lambda (th)
                              (theme-looper-enable-theme (intern th)
                                                         t))
                    :update-fn #'theme-looper--try-activating-theme)
        (message "theme-looper: package 'ivy' is not installed!")))
    
    (defun theme-looper--try-activating-theme ()
      (if (member (intern ivy-text)
                  (theme-looper--get-looped-themes))
          (theme-looper-enable-theme (intern ivy-text)
                                     nil)))

**Comment by 4goodapp** [comment]
I just test it but it works the same as the other theme-looper-select-theme.
And I wonder, if it select and activate the matched theme while typing a themes name, then it should be able to activated a theme while scrolling through the list, right? Or maybe I misunderstood what you mean by:

> I have a snippet in place that tries to find a theme and enable it while you type.

**Comment by myTerminal** [comment]
> And I wonder, if it select and activate the matched theme while typing a themes name, then it should be able to activated a theme while scrolling through the list, right?

Yes, it should. But the argument `:update-fn` that I was imagining to be capable of working that way (reporting changes to selection on scrolling) only gets called when you type something in the mini-buffer.

**Comment by 4goodapp** [comment]
Can You post a gift of the function working please?

**Comment by myTerminal** [comment]
Also, I came across [this](https://github.com/syohex/emacs-helm-themes) a little too late.

That is like an implementation to work with the other ecosystem. I guess this is where our original discussion about adding ivy-integration must have started?

**Comment by myTerminal** [comment]
> Can You post a gift of the function working please?

[That](https://github.com/myTerminal/theme-looper/issues/8#issuecomment-486055979) is the working code that I have right now. Are you asking for a gist specifically?

**Comment by 4goodapp** [comment]
> Are you asking for a gist specifically?

no, a gif image showing the function in action - like trying to change a theme by typing the name.

**Comment by 4goodapp** [comment]
> Also, I came across this a little too late.

Ohh, I didn't know about this, I just test it and it work the same as your implementation with Ivy.

**Comment by 4goodapp** [comment]
And there is `counsel-load-theme` theme too btw.

**Comment by myTerminal** [comment]
There you go...

![theme-looper-select-theme-wip](https://user-images.githubusercontent.com/2478559/56703859-6ed20880-66d0-11e9-9570-fc86e391738c.gif)

**Comment by myTerminal** [comment]
> And there is `counsel-load-theme` theme too btw.

So there is a way to do that but indirectly.

**Comment by myTerminal** [comment]
[Done](https://github.com/myTerminal/theme-looper/commit/f3b2f82c29d91904180c83366402a62d86d0193f).

I referred to the code from `counsel-load-theme` where I learned that one can browse through the options and select them, both the same time using `ivy-previous-line-and-call` and `ivy-next-line-and-call`. I created a local keymap to bound `<up>`, `<down>`, `C-p` and `C-n` to those functions and we now have what we have been looking for.

**Comment by 4goodapp** [comment]
Ohh cool, Testing it.

**Comment by 4goodapp** [comment]
It works, 
I have to disable [interaction-log-mode](https://github.com/michael-heerdegen/interaction-log.el) though, otherwise I get this message for each scroll: 

![image](https://user-images.githubusercontent.com/6249230/56739703-e3ec1f00-675e-11e9-882b-8ce98f72bf37.png)

___

Another issue am having is typing a theme doesn't work.
A friend gave me this snippet where typing works but for some reason, I can't call the function twice - like I have to restart Emacs for each call:

``` lisp
(defvar initial-theme nil)

(defun my-load-theme ()
  (interactive)
  (setq initial-theme (copy-sequence (car custom-enabled-themes)))
  (ivy-read "Load custom theme: "
            (mapcar 'symbol-name
                    (custom-available-themes))
            :action #'counsel-load-theme-action
            :caller 'counsel-load-theme
            :unwind #'my--load-theme-unwind-fn
            :update-fn #'my--load-theme-update-fn
            ))

(defun my--load-theme-update-fn ()
  (let ((current (ivy-state-current ivy-last))
        (inhibit-message t))
    (when (member current (mapcar #'symbol-name (custom-available-themes)))
      (ivy-call))))

(defun my--load-theme-unwind-fn ()
  (when initial-theme
    (counsel-load-theme-action (symbol-name initial-theme))))
```
It is adapted from the function `counsel-switch-buffer`.

**Comment by myTerminal** [comment]
> I can't call the function twice - like I have to restart Emacs for each call

I tried the code you shared and it worked after a minor change: I had to remove `copy-sequence` call. It worked for me perfectly, not sure why you could not run it more than once in an Emacs session.

In fact, I learned a lot from the code and updated my implementation with many elements from it. Now we can switch themes by scrolling as well as filtering(typing). Also as a plus, the previously activated theme is restored when the menu is exited if no theme was actually selected but a few were only previewed. I loved that idea and grabbed it too!

Could you try with the latest code now? Also not sure if the unnecessary logging still exists with the interaction-log-mode.

**Comment by 4goodapp** [comment]
Just tested it, It works fine.

I still get the log message when (unless I disable interaction-log-mode).

**Comment by 4goodapp** [comment]
Just tested it, It works fine.

I still get the log message when (unless I disable interaction-log-mode).
He added the line containing `(inhibit-message t)` to remove it btw.
Do you have [interaction-log](https://github.com/michael-heerdegen/interaction-log.el) installed?

> Now we can switch themes by scrolling as well as filtering(typing). 

Yes, bother are working  correctly now.

**Comment by myTerminal** [comment]
> He added the line containing `(inhibit-message t)` to remove it btw

I know, but that does not work on Emacs 26.1. What version of Emacs did you test it with?

I'll probably place the line in there, better than not having anything. Also, I will look for another way that works on 26.1.

> Do you have interaction-log installed?

No. I think I used to have it installed at one point of time, but is not there now.

**Comment by 4goodapp** [comment]
> What version of Emacs did you test it with?

Am using 26.1 too. 

> I'll probably place the line in there, better than not having anything. 

I placed it there and it's working now, not sure if I place it at the right place though.

question:
Is there a way to loops through ALL installed themes? Not just the favorites one in  `theme-looper-set-favorite-themes`.
I think having this, this will be a more interactive version compared to  `counsel-load-theme` or the  built-in `load-theme` function.

**Comment by 4goodapp** [comment]
> Also as a plus, the previously activated theme is restored when the menu is exited if no theme was actually selected but a few were only previewed.

I guess you mean by selecting overcast as your theme, calling `theme-looper-select-theme` again, overcast is selected by default in the list.

If that's what you mean, that's what I was expecting too but the list is reset at every call of `theme-looper-select-theme` here.

**Comment by myTerminal** [comment]
> Is there a way to loops through ALL installed themes?

In fact, if you do not set any favorites, `theme-looper` does it by default in the essence that you did not narrow down the scope by specifying your choice.

> I guess you mean by selecting overcast as your theme, calling `theme-looper-select-theme` again, overcast is selected by default in the list.

No, I meant that suppose you have `overcast` enabled and you start the ivy interface to select a theme. You step on a few items in the list by either scrolling or by typing a name and you are presented with a preview. If you hit the return key, the selected theme is enabled. However, if you exit the interface without selecting a theme, the previously selected theme is restored (enabled back in your current session).

About starting the list with the currently enabled theme, I'll still have to implement that.

**Comment by 4goodapp** [comment]
> In fact, if you do not set any favorites, theme-looper does it by default in the essence that you did not narrow down the scope by specifying your choice.

Not that I need it really but I think having a separate function would be better I think.

> No, I meant that suppose you have overcast enabled and you start the ivy interface to select a theme...

Ohh yeah, I got it now. This is an expected behavior - enabling a theme only if you hit Enter. 

> About starting the list with the currently enabled theme, I'll still have to implement that.

Cool!

**Comment by myTerminal** [comment]
The list now starts with the currently enabled theme selected and we now have a separate method `theme-looper-select-theme-from-all` that allows selection from all available themes.

Also, I tried `interaction-log` and did not see any unrequired logs. Below is what I saw on starting the interface, moving up and down a couple of times and finally selecting a theme.

<img width="242" alt="theme-looper-interaction-log-logs" src="https://user-images.githubusercontent.com/2478559/56857315-8c51dd00-6931-11e9-8138-34ec2aa647f1.png">

**Comment by 4goodapp** [comment]
PERFECT!!!

**Comment by 4goodapp** [comment]
Can I share it on [r/emacs](https://www.reddit.com/r/emacs/)?

**Comment by myTerminal** [comment]
> Now we can even browser many light or dark themes by just typing "dark" or "light" too.

Correct, which is a great bonus :)

> Can I share it on r/emacs?

Sure, why not?

But, do you not see the logs anymore?

**Comment by 4goodapp** [comment]
> But, do you not see the logs anymore?

If I activate `interaction-log-mode`, yes, it appears at every scroll.

**Comment by myTerminal** [comment]
I tried the `inhibit-message` variable and the results were the same for me in both cases, with or without it.

The usual *Messages* log buffer does not have any logs (which is correct, as the entire code around this feature is log-free), and the *Emacs Log* buffer from `interaction-log` shows every single key-stroke, which I think is also correct because that is the exact purpose of using that package.

Apart from the logs, everything else seems to be in place. What do you suggest?

**Comment by 4goodapp** [comment]
Well, this is weird. Maybe it's just me with my messy init file lol. (You can forget about it)
___
Ohh by the way I notice the list doesn't loop. Maybe you should add that?

**Comment by myTerminal** [comment]
As far as I've seen, lists provided by `helm` and `ivy` are never looped. That also helps you to be able to move to the start or the end of the list.

I did a small research to find any examples and could not find any. However, I found a parameter called `dynamic-collection` in the API, which I think I can use to create an illusion that the list is being looped.

I imagine I can repeat the list three times (a copy of the collection before and another after the actual collection to be shown). User's selection would be always in the middle list. As soon as they step on the third list, it would become the middle list and (eliminating the first one,) a new list would be appended at the at of the collection to make an illusion that the list is cyclic. All this can be very well achieved. However, I realized that the length of the list shown (which is displayed to the left of the ivy prompt) would read a number which would be three times larger than the actual number of themes being looped, and that would definitely confuse the user. Which made me realize this approach is not quite feasible.

What do you think?

**Comment by 4goodapp** [comment]
a friend suggested   `(let ((ivy-wrap t))` like this:

```lisp
  (if (featurep 'ivy)
      (let ((ivy-wrap t))
        (ivy-read "theme-looper: "
                  themes-collection
                  :preselect (symbol-name (theme-looper--get-current-theme))
                  :update-fn 'theme-looper--preview-theme
                  :action (lambda (th)
                            (theme-looper-enable-theme (intern th)))
                  :unwind 'theme-looper--restore-theme)
        (message "theme-looper: package 'ivy' is not installed!"))))
```

It works here.

**Comment by myTerminal** [comment]
That indeed works, thanks!

Just pushed the change. Please try when possible.

**Comment by 4goodapp** [comment]
It works perfectly here.

**Comment by myTerminal** [comment]
I guess we have much more than what we planned for this one :)

Thanks for your help with snippets with `ivy-last` and `ivy-wrap`. I'm closing the issue.
